#!/bin/bash
# QUICK REFERENCE - NRJ Morgen Ultimate 2026 Search
# Bruk dette for å huske hvor det perfekte søket ligger

echo "╔═══════════════════════════════════════════════════════════════╗"
echo "║     🔍 NRJ MORGEN - ULTIMATE 2026 SØK REFERANSE            ║"
echo "╚═══════════════════════════════════════════════════════════════╝"
echo ""
echo "📁 HOVEDFIL:"
echo "   /root/.openclaw/workspace/.config/ULTIMATE_2026_SEARCH.md"
echo ""
echo "📝 FULL DOKUMENTASJON:"
echo "   - 100+ overvåkede navn"
echo "   - 80+ søkekategorier"
echo "   - Alle reality-programmer 2026"
echo "   - Triggere og snakkiser"
echo "   - Automatisert overvåking"
echo ""
echo "🔧 IMPLEMENTASJON:"
echo "   Script: /root/.openclaw/workspace/scripts/brave-news-search.py"
echo "   Rutine: /root/.openclaw/workspace/scripts/morning-routine.sh"
echo ""
echo "📊 GIT REPO:"
echo "   https://github.com/baarli/nrj-morgen-workspace"
echo ""
echo "⚡ HURTIGKOMMANDOER:"
echo "   cat /root/.openclaw/workspace/.config/ULTIMATE_2026_SEARCH.md"
echo "   cd /root/.openclaw/workspace && git status"
echo "   cd /root/.openclaw/workspace/scripts && python3 brave-news-search.py"
echo ""
echo "🔄 SIST OPPDATERT: 2026-02-21"
echo "✅ VERSJON: Ultimate 2026 v1.0"
echo ""
