#!/usr/bin/env python3
"""
Vev Self-Improvement System
Weekly analysis and automatic improvement
Creates skills from patterns
"""
import os
import json
from datetime import datetime, timedelta

WORKSPACE = "/root/.openclaw/workspace"
LEARNING_DB = f"{WORKSPACE}/brain/learning-database.json"
SKILLS_DIR = f"{WORKSPACE}/skills"

def load_learning_db():
    if os.path.exists(LEARNING_DB):
        with open(LEARNING_DB) as f:
            return json.load(f)
    return {"sessions": [], "learnings": []}

def analyze_weekly_performance():
    """Analyze this week's performance vs previous weeks"""
    db = load_learning_db()
    
    if len(db["sessions"]) < 7:
        return None
    
    # Split into weeks
    sessions = db["sessions"]
    mid = len(sessions) // 2
    
    recent_week = sessions[-mid:]
    previous_week = sessions[:mid]
    
    recent_stats = {
        "sessions": len(recent_week),
        "avg_files": sum(s.get("files_changed", 0) for s in recent_week) / len(recent_week),
        "task_types": set()
    }
    
    prev_stats = {
        "sessions": len(previous_week),
        "avg_files": sum(s.get("files_changed", 0) for s in previous_week) / len(previous_week),
        "task_types": set()
    }
    
    for s in recent_week:
        recent_stats["task_types"].update(s.get("task_types", []))
    
    for s in previous_week:
        prev_stats["task_types"].update(s.get("task_types", []))
    
    return {
        "recent": recent_stats,
        "previous": prev_stats,
        "improvement": recent_stats["avg_files"] > prev_stats["avg_files"]
    }

def create_skill_from_pattern(pattern_name, description, examples):
    """Create a new skill from learned pattern"""
    skill_dir = f"{SKILLS_DIR}/auto-{pattern_name.lower().replace(' ', '-')}"
    os.makedirs(skill_dir, exist_ok=True)
    
    skill_md = f"""# {pattern_name}

**Type:** Auto-generated Skill  
**Created:** {datetime.now().strftime('%Y-%m-%d')}  
**Source:** Pattern recognition from learning database

## Description

{description}

## Examples

"""
    for ex in examples[:3]:
        skill_md += f"- {ex}\n"
    
    skill_md += f"""
## Best Practices

Based on previous successful executions:

1. Plan before executing
2. Test in isolation first
3. Document what works
4. Learn from mistakes

---

*This skill was automatically generated by Vev's self-improvement system.*
"""
    
    with open(f"{skill_dir}/SKILL.md", 'w') as f:
        f.write(skill_md)
    
    return skill_dir

def generate_improvement_recommendations():
    """Generate recommendations based on patterns"""
    db = load_learning_db()
    
    recommendations = []
    
    # Check for repeated errors
    error_patterns = [l for l in db.get("learnings", []) if "error" in l.get("text", "").lower()]
    if len(error_patterns) > 3:
        recommendations.append("Consider creating error-handling procedures")
    
    # Check for frequent task types
    from collections import Counter
    task_counts = Counter()
    for session in db.get("sessions", []):
        for task in session.get("task_types", []):
            task_counts[task] += 1
    
    for task, count in task_counts.items():
        if count >= 3:
            recommendations.append(f"Create dedicated skill for '{task}' (done {count} times)")
    
    return recommendations

def main():
    print("=" * 60)
    print("🔄 SELF-IMPROVEMENT SYSTEM")
    print("=" * 60)
    print()
    
    # Analyze weekly performance
    performance = analyze_weekly_performance()
    
    if performance:
        print("📊 Weekly Performance Analysis:")
        print(f"   Recent: {performance['recent']['sessions']} sessions, "
              f"{performance['recent']['avg_files']:.1f} files avg")
        print(f"   Previous: {performance['previous']['sessions']} sessions, "
              f"{performance['previous']['avg_files']:.1f} files avg")
        print(f"   Improvement: {'✅ Yes' if performance['improvement'] else '⚠️  No'}")
        print()
    
    # Generate recommendations
    recommendations = generate_improvement_recommendations()
    
    if recommendations:
        print("💡 Improvement Recommendations:")
        for i, rec in enumerate(recommendations, 1):
            print(f"   {i}. {rec}")
        print()
    
    # Create skills from frequent patterns
    db = load_learning_db()
    from collections import Counter
    task_counts = Counter()
    for session in db.get("sessions", []):
        for task in session.get("task_types", []):
            task_counts[task] += 1
    
    created_skills = []
    for task, count in task_counts.items():
        if count >= 3:
            skill_path = create_skill_from_pattern(
                task.replace('_', ' ').title(),
                f"Auto-generated skill based on {count} successful executions",
                [s.get("learnings", [""])[0] for s in db["sessions"] if task in s.get("task_types", [])]
            )
            created_skills.append(skill_path)
    
    if created_skills:
        print("🛠️  Created Skills:")
        for skill in created_skills:
            print(f"   - {skill}")
        print()
    
    print("✅ Self-improvement cycle complete!")

if __name__ == "__main__":
    main()
