#!/usr/bin/env python3
"""
Vev Conversation Summarizer
Oppsummerer lange samtaler automatisk
"""
import os
import sys
from datetime import datetime
from pathlib import Path

WORKSPACE = "/root/.openclaw/workspace"
CONVERSATIONS_DIR = f"{WORKSPACE}/brain/conversations"

def ensure_dirs():
    os.makedirs(CONVERSATIONS_DIR, exist_ok=True)

def summarize_conversation():
    ensure_dirs()
    
    print("=" * 60)
    print("📝 CONVERSATION SUMMARIZER")
    print("=" * 60)
    print()
    
    print("📋 What was this conversation about?")
    print("   (One line summary)")
    topic = input("   > ").strip()
    
    print()
    print("✅ What was accomplished?")
    print("   (Press Enter with empty line when done)")
    accomplishments = []
    while True:
        item = input("   > ").strip()
        if not item:
            break
        accomplishments.append(item)
    
    print()
    print("💡 Key insights/decisions?")
    print("   (Press Enter with empty line when done)")
    insights = []
    while True:
        item = input("   > ").strip()
        if not item:
            break
        insights.append(item)
    
    print()
    print("📁 Files modified/created?")
    print("   (Press Enter with empty line when done)")
    files = []
    while True:
        item = input("   > ").strip()
        if not item:
            break
        files.append(item)
    
    # Generate summary
    timestamp = datetime.now().strftime('%Y-%m-%d_%H-%M')
    summary_file = f"{CONVERSATIONS_DIR}/conversation_{timestamp}.md"
    
    with open(summary_file, 'w') as f:
        f.write(f"# Conversation Summary\n\n")
        f.write(f"**Date:** {datetime.now().strftime('%Y-%m-%d %H:%M')}\n\n")
        f.write(f"## Topic\n{topic}\n\n")
        
        if accomplishments:
            f.write("## Accomplishments\n")
            for a in accomplishments:
                f.write(f"- [x] {a}\n")
            f.write("\n")
        
        if insights:
            f.write("## Key Insights\n")
            for i in insights:
                f.write(f"- {i}\n")
            f.write("\n")
        
        if files:
            f.write("## Files Modified\n")
            for file in files:
                f.write(f"- `{file}`\n")
            f.write("\n")
        
        f.write("---\n")
        f.write(f"*Generated by Vev Conversation Summarizer*\n")
    
    print()
    print("=" * 60)
    print("✅ Conversation summarized!")
    print()
    print(f"📄 {topic}")
    print(f"   ✅ {len(accomplishments)} accomplishments")
    print(f"   💡 {len(insights)} insights")
    print(f"   📁 {len(files)} files")
    print()
    print(f"📁 Saved to: {summary_file}")
    print("=" * 60)

def list_recent_summaries():
    """List recent conversation summaries"""
    ensure_dirs()
    
    print("=" * 60)
    print("📚 RECENT CONVERSATIONS")
    print("=" * 60)
    print()
    
    files = sorted(Path(CONVERSATIONS_DIR).glob("*.md"), key=lambda x: x.stat().st_mtime, reverse=True)[:10]
    
    if not files:
        print("📝 No conversation summaries yet!")
        return
    
    for f in files:
        content = f.read_text()
        # Extract topic
        topic = "Unknown"
        for line in content.split('\n'):
            if line.startswith('## Topic'):
                topic = content.split('## Topic')[1].split('##')[0].strip()
                break
        date = f.stem.replace('conversation_', '').replace('_', ' ')
        print(f"   📄 {date}: {topic[:50]}...")
    
    print()
    print(f"Total: {len(list(Path(CONVERSATIONS_DIR).glob('*.md')))} conversations")
    print("=" * 60)

if __name__ == "__main__":
    if len(sys.argv) > 1 and sys.argv[1] == "--list":
        list_recent_summaries()
    else:
        summarize_conversation()
