#!/usr/bin/env python3
"""
Vev Pattern Analyzer
Analyzes learning database for patterns and trends
Updates MEMORY.md automatically
"""
import os
import json
from datetime import datetime, timedelta
from collections import Counter

WORKSPACE = "/root/.openclaw/workspace"
LEARNING_DB = f"{WORKSPACE}/brain/learning-database.json"
MEMORY_FILE = f"{WORKSPACE}/MEMORY.md"

def load_learning_db():
    if os.path.exists(LEARNING_DB):
        with open(LEARNING_DB) as f:
            return json.load(f)
    return {"sessions": [], "learnings": []}

def analyze_patterns():
    """Analyze learning database for patterns"""
    db = load_learning_db()
    
    if not db["sessions"]:
        return None
    
    patterns = {
        "total_sessions": len(db["sessions"]),
        "total_learnings": len(db["learnings"]),
        "task_type_frequency": {},
        "complexity_distribution": {},
        "most_active_days": [],
        "improvement_trends": []
    }
    
    # Count task types
    task_counts = Counter()
    complexity_counts = Counter()
    daily_activity = Counter()
    
    for session in db["sessions"]:
        # Task types
        for task_type in session.get("task_types", []):
            task_counts[task_type] += 1
        
        # Complexity
        complexity = session.get("complexity", "unknown")
        complexity_counts[complexity] += 1
        
        # Daily activity
        date = session.get("date", "unknown")
        daily_activity[date] += 1
    
    patterns["task_type_frequency"] = dict(task_counts.most_common())
    patterns["complexity_distribution"] = dict(complexity_counts)
    patterns["most_active_days"] = daily_activity.most_common(5)
    
    # Detect improvement trends
    if len(db["sessions"]) >= 3:
        recent = db["sessions"][-3:]
        avg_files_recent = sum(s.get("files_changed", 0) for s in recent) / 3
        older = db["sessions"][:3] if len(db["sessions"]) >= 6 else db["sessions"][:len(db["sessions"])//2]
        avg_files_older = sum(s.get("files_changed", 0) for s in older) / len(older)
        
        if avg_files_recent > avg_files_older * 1.2:
            patterns["improvement_trends"].append("Increasing productivity - more files per session")
        elif avg_files_recent < avg_files_older * 0.8:
            patterns["improvement_trends"].append("Focusing on quality over quantity")
        else:
            patterns["improvement_trends"].append("Consistent productivity")
    
    return patterns

def update_memory_md(patterns):
    """Update MEMORY.md with pattern insights"""
    if not patterns:
        return
    
    insight_section = f"""

---

## 🤖 AUTO-GENERATED INSIGHTS ({datetime.now().strftime('%Y-%m-%d')})

**Pattern Analysis:**
- Total sessions analyzed: {patterns['total_sessions']}
- Total learnings captured: {patterns['total_learnings']}

**Most Frequent Task Types:**
"""
    
    for task, count in list(patterns['task_type_frequency'].items())[:5]:
        insight_section += f"- {task}: {count} times\n"
    
    insight_section += f"""
**Complexity Distribution:**
"""
    for complexity, count in patterns['complexity_distribution'].items():
        insight_section += f"- {complexity}: {count} sessions\n"
    
    if patterns['improvement_trends']:
        insight_section += f"""
**Improvement Trends:**
"""
        for trend in patterns['improvement_trends']:
            insight_section += f"- {trend}\n"
    
    insight_section += """
*These insights are automatically generated by the pattern analyzer.*
"""
    
    # Append to MEMORY.md
    with open(MEMORY_FILE, 'a') as f:
        f.write(insight_section)
    
    return insight_section

def main():
    print("=" * 60)
    print("🔍 PATTERN ANALYZER")
    print("=" * 60)
    print()
    
    patterns = analyze_patterns()
    
    if not patterns:
        print("Not enough data for pattern analysis yet.")
        print("Continue working - I'll learn from your activity!")
        return
    
    print(f"📊 Analyzed {patterns['total_sessions']} sessions")
    print(f"📚 Found {patterns['total_learnings']} learnings")
    print()
    
    print("Most frequent tasks:")
    for task, count in list(patterns['task_type_frequency'].items())[:5]:
        print(f"   - {task}: {count} times")
    
    print()
    print("Updating MEMORY.md...")
    update_memory_md(patterns)
    print("✅ Done!")

if __name__ == "__main__":
    main()
